NUSCENES:
## DATLOADER ####################################################################
    SAMPLE_MODE: "scene"    # "camera": samples based on each camera's FOV
                             #    this mode only includes point cloud and annotations 
                             #    that are visible inside the image
                             # "scene" sample contains all sensors in one scene.
                             # Both modes return data in vehicle's coordinate system

    REF_POSE_CHANNEL: "LIDAR_TOP"  # reference vehicle pose for "scene" sample mode
    GEN_2D_BBOX: False         # generate 2D bboxes from 3D annotations
    LIDAR_SWEEPS: 1           # number of LIDAR sweeps
    RADAR_SWEEPS: 1           # number of Radar sweeps
    BOX_VELOCITY: False        # calculate velocity for each annotation
    MAX_BOX_DIST: 0           # Maximum box distance in m to include in annotations 
                              # (0 for no limit on distance)
    ANN_VIS_LEVELS: ['2', '3', '4']   ## annotation visibility levels

## sensors to include in the databse. All sensors not in this list are ignored.
    SENSORS: [
      "RADAR_FRONT_LEFT",
      "RADAR_FRONT_RIGHT",
      "RADAR_FRONT",
      "RADAR_BACK_LEFT",
      "RADAR_BACK_RIGHT",
    ]

## categories to include in database and their corresponding name mapping.
## Any category not in this dictionary is ignored.
    CATEGORIES: {
       'movable_object.barrier': 'barrier',
        'vehicle.bicycle': 'bicycle',
        'vehicle.bus.bendy': 'bus',
        'vehicle.bus.rigid': 'bus',
        'vehicle.car': 'car',
        'vehicle.construction': 'construction_vehicle',
        'vehicle.motorcycle': 'motorcycle',
        'human.pedestrian.adult': 'pedestrian',
        'human.pedestrian.child': 'pedestrian',
        'human.pedestrian.construction_worker': 'pedestrian',
        'human.pedestrian.police_officer': 'pedestrian',
        'movable_object.trafficcone': 'traffic_cone',
        'vehicle.trailer': 'trailer',
        'vehicle.truck': 'truck'
    }

## Category IDs
    CAT_ID: {
      'car': 1, 
      'truck': 2, 
      'bus': 3,
      'trailer': 4, 
      'construction_vehicle': 5, 
      'pedestrian': 6, 
      'motorcycle': 7, 
      'bicycle': 8,
      'traffic_cone': 9,
      'barrier': 10
    }

## MISC ########################################################################
    VERBOSE: False                     # enable verbose mode
    IMG_ID_LEN: 8                     # length of string image ID
    PC_MIN_DIST: 1                    # Ignore points closer than this distance (m)
    CONSOLE_LOG_LEVEL: "WARNING"         # logging level for console
    FILE_LOG_LEVEL: "WARNING"         # logging level for the log file
    LOG_OUT_DIR: "../../output/logs"  # logging output directory
